# Generated by Django 4.2.10 on 2024-02-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0005_alter_profile_options_alter_profile_managers_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={},
        ),
        migrations.AlterModelManagers(
            name="profile",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="profile",
            name="date_joined",
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(max_length=50),
        ),
    ]
