# Generated by Django 4.2.10 on 2024-02-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0007_alter_profile_first_name_alter_profile_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(default="User", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="groups",
            field=models.ManyToManyField(related_name="user_profiles", to="auth.group"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user_permissions",
            field=models.ManyToManyField(
                related_name="user_profiles", to="auth.permission"
            ),
        ),
    ]
