# Generated by Django 4.2.10 on 2024-02-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0009_alter_profile_first_name_alter_profile_groups_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
