# Generated by Django 4.2.10 on 2024-02-25 07:32

from django.db import migrations, models


def set_default_first_name(apps, schema_editor):
    Profile = apps.get_model("authentication", "Profile")
    Profile.objects.filter(first_name=None).update(first_name="Unknown")


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0013_alter_profile_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(default="Unknown", max_length=50, null=True),
        ),
    ]
