# Generated by Django 4.2.10 on 2024-03-10 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_remove_payment_payment_id_payment_id_payment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
