# Generated by Django 4.2.10 on 2024-02-25 09:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=100, verbose_name="cost"
                    ),
                ),
                ("rides", models.IntegerField()),
                ("duration", models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=100, verbose_name="balance"
                    ),
                ),
                (
                    "account_name",
                    models.CharField(max_length=250, verbose_name="account name"),
                ),
                (
                    "account_number",
                    models.CharField(max_length=100, verbose_name="account number"),
                ),
                ("bank", models.CharField(max_length=100, verbose_name="bank")),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="phone number"),
                ),
                ("password", models.CharField(max_length=200, verbose_name="password")),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
