# Generated by Django 4.2.10 on 2024-02-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=100, verbose_name="cost"
                    ),
                ),
                ("rides", models.IntegerField()),
                ("duration", models.DurationField()),
            ],
        ),
    ]
