# Generated by Django 4.2.10 on 2024-02-26 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Wallet",
        ),
    ]
