# Generated by Django 4.2.10 on 2024-02-25 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_alter_profile_first_name_alter_profile_last_name"),
        ("analytics", "0003_statistics_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statistics",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authentication.profile",
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authentication.profile",
            ),
        ),
    ]
