# Generated by Django 4.2.10 on 2024-02-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cycle",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
