# Generated by Django 4.2.10 on 2024-02-25 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0008_alter_profile_first_name_alter_profile_groups_and_more",
        ),
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="authentication.profile"
            ),
        ),
        migrations.AlterField(
            model_name="cycle",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="authentication.profile"
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="authentication.profile"
            ),
        ),
    ]
