# Generated by Django 4.2.10 on 2024-02-26 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_cycle_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='lock',
        ),
        migrations.AddField(
            model_name='ride',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.cycle')),
                ('hub', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.hub')),
            ],
        ),
    ]
