# Generated by Django 4.2.10 on 2024-03-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_remove_cycle_lock_ride_cost_lock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="status",
        ),
        migrations.AddField(
            model_name="booking",
            name="cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
