# Generated by Django 4.2.10 on 2024-03-08 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_lock_arduino_port"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lock",
            name="hub",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="booking.hub"
            ),
        ),
    ]
