# Generated by Django 4.2.10 on 2024-03-09 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0007_alter_ride_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lock",
            name="cycle",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.cycle",
            ),
        ),
    ]
