# Generated by Django 4.2.10 on 2024-03-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0009_booking_book_time_booking_hub"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cost",
            field=models.IntegerField(default=0),
        ),
    ]
