# Generated by Django 4.2.10 on 2024-02-23 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("air_issues", models.BooleanField()),
                ("sound_issues", models.BooleanField()),
                ("brake_issues", models.BooleanField()),
                ("chain_issues", models.BooleanField()),
                ("detailed_issues", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.profile",
                    ),
                ),
            ],
        ),
    ]
